---
abstract: 'Interface to the Saasu online accounting platform!'
author:
  - 'Lenz Gschwendtner, C<< <norbu09 at cpan.org> >>'
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Saasu
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  LWP::UserAgent: 0
  XML::TreePP: 0
  perl: 5.01
resources:
  bugtracker: https://github.com/norbu09/Net-Saasu/issues
  homepage: http://springtimesoft.com/lenz
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/norbu09/Net-Saasu.git
version: 0.1
